<%@ Page Title="" Language="C#" MasterPageFile="~/AladinPage.Master" AutoEventWireup="true" CodeBehind="AnalysisCommons.aspx.cs" Inherits="Lab2.AnalysisCommons" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <div class="row justify-content-center align-items-center" style="height: 150px">
        <div class="col-md-8">
            <div class="p-3 border border-dark bg-light">
                <div class="p-3 border border-dark bg-info">
                    <h2>Analysis Commons</h2>
                </div>
                <div class="col-md-4">
                    <asp:Label ID="lblReqTitle" runat="server" Text="Send Friend Request" ForeColor="Purple" Font-Size="Larger" />
                    <table>
                        <tr>
                            <td>Friend Email:</td>
                            <td>
                                <asp:TextBox ID="txtFrEmail" runat="server"></asp:TextBox>
                            </td>
                            <td>
                                <asp:Button ID="btnSearch" runat="server" Text="Search" OnClick="btnSearch_Click" />
                            </td>
                            <td>
                                <asp:Label ID="lblMessage" runat="server" Text=""></asp:Label>
                            </td>
                        </tr>
                        <tr>
                            <td>Users:</td>
                            <td>
                                <asp:TextBox ID="txtSrResult" runat="server" ReadOnly="true"></asp:TextBox>
                            </td>
                            <td>
                                <asp:Button ID="btnSend" runat="server" Text="Invite" OnClick="btnSend_Click" Enabled="false" />
                                <asp:Label ID="lblInviteResult" runat="server" Text=""></asp:Label>
                            </td>
                        </tr>
                    </table>
                </div>

                <hr />


                <div class="col-md-4">
                    <asp:Label ID="lblInvTitle" runat="server" Text="Friend Invitation" ForeColor="Purple" Font-Size="Larger" />
                    <table>
                        <tr>
                            <td style="width: 100px">
                                <asp:DropDownList ID="ddlInvitation" runat="server" DataSourceID="srcInvitation" DataTextField="SenderUsername" DataValueField="SenderUsername"></asp:DropDownList>
                            </td>
                            <td>
                                <asp:Button ID="btnAccept" runat="server" Text="accept" OnClick="btnAccept_Click" />
                            </td>
                            <td>
                                <asp:Label ID="lblAcptResult" runat="server" Text=""></asp:Label>
                            </td>
                        </tr>
                    </table>

                    <asp:SqlDataSource ID="srcInvitation" runat="server" ConnectionString="<%$ ConnectionStrings:Lab3CS %>"
                        SelectCommand="SELECT SenderUsername FROM Friendship where ReceiverUsername = @username AND inviteStatus ='pending';">
                        <SelectParameters>
                            <asp:SessionParameter Name="username" SessionField="username" Type="String" />
                        </SelectParameters>
                    </asp:SqlDataSource>


                    <hr />


                    <asp:Label ID="lblFriendList" runat="server" Text="Friend List" ForeColor="Purple" Font-Size="Larger" />
                    <asp:GridView ID="grdFriends" runat="server" DataSourceID="srcGrdFriends" AutoGenerateDeleteButton="true" DataKeyNames="friend"
                        AllowSorting="true" EmptyDataText="No Friends, please send invitation!">
                    </asp:GridView>

                    <asp:SqlDataSource ID="srcGrdFriends" runat="server" ConnectionString="<%$ ConnectionStrings:Lab3CS %>"
                        SelectCommand="select senderUsername AS friend from Friendship
                            where InviteStatus = 'done' AND senderUsername != @user AND receiverusername = @user
                            union
                           select receiverUsername AS friend from Friendship
                            where InviteStatus = 'done' AND  senderUsername = @user AND receiverUsername != @user;"
                        DeleteCommand="Delete Friendship where (receiverusername = @user AND senderUsername=@friend) or (receiverusername = @friend AND senderUsername=@user)">
                        <SelectParameters>
                            <asp:SessionParameter Type="String" Name="user" SessionField="username" />
                        </SelectParameters>
                        <DeleteParameters>
                            <asp:Parameter Type="String" Name="friend" />
                            <asp:SessionParameter Type="String" Name="user" SessionField="username" />
                        </DeleteParameters>
                    </asp:SqlDataSource>

                </div>
                <hr />

                <asp:Label ID="lblShareAnalysis" runat="server" Text="Share Analysis View" ForeColor="Purple" Font-Size="Larger" />
                <table>
                    <tr>
                        <td>Choose a Friend</td>
                        <td style="width: 100px">
                            <asp:DropDownList ID="ddlShareFr" runat="server" DataSourceID="src_ddlShareFr" DataTextField="friend" DataValueField="friend"></asp:DropDownList>
                        </td>
                    </tr>
                    <tr>
                        <td>Choose Analysis</td>
                        <td style="width: 100px">
                            <asp:DropDownList ID="ddlShareAnalysis" runat="server" DataSourceID="src_ddlAnalysis" DataTextField="AnalysisContent" DataValueField="AnalysisID"></asp:DropDownList>
                        </td>
                    </tr>
                    <tr>
                        <td>Share Reason:</td>
                        <td>
                            <asp:TextBox ID="txtShareReason" runat="server"></asp:TextBox>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <asp:Button ID="btnShare" runat="server" Text="Share" OnClick="btnShare_Click" />
                        </td>
                        <td>
                            <asp:Label ID="lblShareConfirm" runat="server" Text=""></asp:Label>
                        </td>
                    </tr>
                </table>

                <asp:SqlDataSource ID="src_ddlAnalysis" runat="server" ConnectionString="<%$ ConnectionStrings:Lab3CS %>"
                    SelectCommand="SELECT AnalysisID, AnalysisContent FROM TextAnalysis AS A INNER JOIN StoryText AS S ON A.TextID = S.TextID AND S.UserID = @userID;">
                    <SelectParameters>
                        <asp:SessionParameter Name="UserID" SessionField="UserID" Type="String" />
                    </SelectParameters>
                </asp:SqlDataSource>

                <asp:SqlDataSource ID="src_ddlShareFr" runat="server" ConnectionString="<%$ ConnectionStrings:Lab3CS %>"
                    SelectCommand="select senderUsername AS friend from Friendship
                            where InviteStatus = 'done' AND senderUsername != @user AND receiverusername = @user
                            union
                           select receiverUsername AS friend from Friendship
                            where InviteStatus = 'done' AND  senderUsername = @user AND receiverUsername != @user;">
                    <SelectParameters>
                        <asp:SessionParameter Type="String" Name="user" SessionField="username" />
                    </SelectParameters>
                </asp:SqlDataSource>
            </div>
        </div>
    </div>


</asp:Content>
